### ISSUE TITLE
Test yaml-config with enum types

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/can-yaml-config-rs#6]
There seems to be something going wrong not really sure where it is happending might be can-yaml-config or can-config

Here is a example that should work!
```
buses:
  can0:
    baudrate: 1000000

enum_types:
  test_enum:
    yes: 2
    no: 42



nodes:
  secu:
    description: Sensor Electronics Control Unit
    object_dictionary:
      test_oe:
        type: test_enum
        access : global
```
